//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TiendaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.ProductoAlmacen = new HashSet<ProductoAlmacen>();
        }
    
        public int idAlmacen { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string nombre { get; set; }
        [DisplayName("Ciudad")]
        [Required]
        public string ciudad { get; set; }
        [DisplayName("Código postal")]
        [Required]
        [RegularExpression("^[0-9]{5}$",
            ErrorMessage = "Codigo postal incorrecto")]
        public string cp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoAlmacen> ProductoAlmacen { get; set; }
    }
}
